version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
#    extra_hosts:
#      - host.docker.internal:host-gateway
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=CLIENT
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.127.38:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=192.168.127.38:2181
